server : server.o
	gcc -Wall server.o -o server
		
server.o : server.c
	gcc -c server.c

clientsender : clientsender.o
	gcc -Wall clientsender.o -o clientsender
		
clientsender.o : clientsender.c
	gcc -c clientsender.c

clientreciever : clientreciever.o
	gcc -Wall clientreciever.o -o clientreciever

clientreciever.o : clientreciever.c
	gcc -c clientreciever.c