/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Submessage Submessage;
typedef struct _DMessage DMessage;


/* --- enums --- */


/* --- messages --- */

struct  _Submessage
{
  ProtobufCMessage base;
  char *value;
};
#define SUBMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&submessage__descriptor) \
    , NULL }


struct  _DMessage
{
  ProtobufCMessage base;
  Submessage *a;
};
#define DMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dmessage__descriptor) \
    , NULL }


/* Submessage methods */
void   submessage__init
                     (Submessage         *message);
size_t submessage__get_packed_size
                     (const Submessage   *message);
size_t submessage__pack
                     (const Submessage   *message,
                      uint8_t             *out);
size_t submessage__pack_to_buffer
                     (const Submessage   *message,
                      ProtobufCBuffer     *buffer);
Submessage *
       submessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   submessage__free_unpacked
                     (Submessage *message,
                      ProtobufCAllocator *allocator);
/* DMessage methods */
void   dmessage__init
                     (DMessage         *message);
size_t dmessage__get_packed_size
                     (const DMessage   *message);
size_t dmessage__pack
                     (const DMessage   *message,
                      uint8_t             *out);
size_t dmessage__pack_to_buffer
                     (const DMessage   *message,
                      ProtobufCBuffer     *buffer);
DMessage *
       dmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dmessage__free_unpacked
                     (DMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Submessage_Closure)
                 (const Submessage *message,
                  void *closure_data);
typedef void (*DMessage_Closure)
                 (const DMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor submessage__descriptor;
extern const ProtobufCMessageDescriptor dmessage__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_2eproto__INCLUDED */
